"""AI 생성 표시(잠금)와 출처 매니페스트.

- disclosure(): 서비스 화면·영상 자막·설명란에 붙일 고지 문구(한국어/영어)
- manifest(): C2PA 매니페스트 구조를 본뜬 JSON 사이드카. 실제 C2PA 서명은 c2patool 등
  외부 도구로 이 사이드카를 입력해 붙인다(서명 키는 운영 환경에서 관리).
"""

from __future__ import annotations

from typing import Optional

from . import __version__
from .ledger import canonical, sha256
from .models import utcnow

GENERATOR = f"STORY8/{__version__}"

# IPTC Digital Source Type 어휘
DST_TRAINED = "http://cv.iptc.org/newscodes/digitalsourcetype/trainedAlgorithmicMedia"
DST_COMPOSITE = "http://cv.iptc.org/newscodes/digitalsourcetype/compositeWithTrainedAlgorithmicMedia"


def disclosure(human_involved: bool, deepfake: bool, grade: Optional[str] = None) -> dict:
    if human_involved:
        ko = "이 작품은 AI를 활용해 제작되었으며, 사람 작가가 기획·편집에 참여했습니다."
        en = "This work was produced with AI assistance; human writers took part in its creation and editing."
    else:
        ko = "이 작품은 AI로 생성되었습니다."
        en = "This work was generated by AI."
    out = {"ko": ko, "en": en, "overlay": "AI 생성 · AI-generated"}
    if deepfake:
        out["deepfake_overlay"] = "실존 인물이 아닌 AI 합성 영상입니다 · Synthetic media, not a real person"
    if grade:
        out["contribution_grade"] = grade
    return out


def manifest(title: str, assets: dict[str, str], human_involved: bool, deepfake: bool,
             ledger_head: str, grade: Optional[str] = None) -> dict:
    """assets: {이름: 내용 문자열} → 내용 해시를 매니페스트에 담는다."""
    actions = [{"action": "c2pa.created", "softwareAgent": GENERATOR,
                "digitalSourceType": DST_COMPOSITE if human_involved else DST_TRAINED}]
    if human_involved:
        actions.append({"action": "c2pa.edited", "description": "human writers' edits recorded in rights ledger"})
    body = {
        "claim_generator": GENERATOR,
        "title": title,
        "created": utcnow(),
        "assertions": [
            {"label": "c2pa.actions", "data": {"actions": actions}},
            {"label": "story8.ai_disclosure", "data": disclosure(human_involved, deepfake, grade)},
            {"label": "story8.rights_ledger", "data": {"head": ledger_head}},
            {"label": "story8.assets", "data": {k: sha256(v) for k, v in assets.items()}},
        ],
        "signature": None,  # c2patool 로 서명 시 채워짐
    }
    body["digest"] = sha256(canonical(body))
    return body
